routes/web.php
<?php

use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Если вам необходимо видеть все sql-запросы, выполняемые к БД на всех страницах вашего сайта можно воспользоваться следующей конструкцией:
DB::listen(function($query) {
  // dump($query->sql, $query->bindings, $query->time);
  // dump($query->sql);
});

Route::view('/', 'welcome');

// 

use App\Http\Controllers\ArticleController;
Route::get('main', [ArticleController::class, 'getArticles']);
Route::get('show-posts-author/{author}', [ArticleController::class, 'getArticlesOfAuthor'])->name('showPostsAuthor');



Route::middleware(['auth:sanctum', 'verified'])->group(function () {
  
  Route::resource('posts', App\Http\Controllers\PostController::class);
  
  // Route::view('create', 'posts.create');
  
  // Route::view('/dashboard','posts.main');
  Route::get('/dashboard', function () {
    // return view('dashboard');
    return redirect('main');
  })->name('dashboard');
  
  
  // More routes here
});

Route::get('/email/verify', function () {
    return view('auth.verify-email');
})->middleware(['auth'])->name('verification.notice');

// Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
//     return view('dashboard');
// })->name('dashboard');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();

    return redirect('/main');
})->middleware(['auth', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    return back()->with('status', 'verification-link-sent');
})->middleware(['auth', 'throttle:6,1'])->name('verification.send');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    
    protected $fillable = [
      'category',
      'header',
      'text',
      'author',
    ];
    
    protected $casts = [
    'is_admin' => 'boolean',
  ];
  
  public function users()
  {
    return $this->belongsToMany('App\Models\User')->withTimestamps();
  }
  
  public function categories()
  {
    return $this->belongsToMany('App\Models\Category')->withTimestamps();
  }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\User;
use App\Models\Category;
use Illuminate\Http\Request;
use Auth;

class PostController extends Controller
{
  /**
  * Display a listing of the resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function index()
  {
    $author = Auth::user()->name;
    $posts = Post::where('author', $author)->get();
    
    return view('posts.index', compact('posts'));
  }
  
  /**
  * Show the form for creating a new resource.
  *
  * @return \Illuminate\Http\Response
  */
  public function create()
  {
    $categories = Category::all();
    
    return view('posts.create', compact('categories'));
  }
  
  /**
  * Store a newly created resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @return \Illuminate\Http\Response
  */
  public function store(Request $request)
  {
    $request->validate([
      'categories'=>'required|array',
      'header'=>'required',
      'text'=>'required'
    ]);
    
    $user = Auth::user();
    
    $post = new Post([
      'header' => $request->get('header'),
      'text' => $request->get('text'),
      'author' => $user->name
    ]);
    
    $categoryNames = $request->get('categories');
    
    foreach ($categoryNames as $categoryName) {
      $category = Category::where('name', $categoryName)->first();
      $category->posts()->save($post);
    }  
    
    $user->posts()->save($post);
    
    return redirect('posts')->with('success', 'Пост успешно добавлен!');
  }
  
  /**
  * Display the specified resource.
  *
  * @param  \App\Models\Post  $post
  * @return \Illuminate\Http\Response
  */
  public function show($id)
  {
    $post = Post::find($id);
    
    return view('posts.show', compact('post'));
  }
  
  /**
  * Show the form for editing the specified resource.
  *
  * @param  \App\Models\Post  $post
  * @return \Illuminate\Http\Response
  */
  public function edit($id)
  {
    $post = Post::find($id);
    $categories = Category::all();
    
    return view('posts.edit', compact('post', 'categories'));
  }
  
  /**
  * Update the specified resource in storage.
  *
  * @param  \Illuminate\Http\Request  $request
  * @param  \App\Models\Post  $post
  * @return \Illuminate\Http\Response
  */
  public function update(Request $request, $id)
  {
    $request->validate([
      'categories'=>'required|array',
      'header'=>'required',
      'text'=>'required'
    ]);
    
    $post = Post::find($id);
    $post->categories()->detach();
    $categoryNames = $request->get('categories');
    
    foreach ($categoryNames as $categoryName) {
      $category = Category::where('name', $categoryName)->first();
      $category->posts()->save($post);
    }  
    $post->header =  $request->get('header');
    $post->text =  $request->get('text');
    $post->save();
    
    return redirect('/posts')->with('success', 'Пост успешно отредактирован!');
  }
  
  /**
  * Remove the specified resource from storage.
  *
  * @param  \App\Models\Post  $post
  * @return \Illuminate\Http\Response
  */
  public function destroy($id)
  {
    $post = Post::find($id);
    $post->categories()->detach();
    $post->users()->detach();
    $post->delete();
    
    return redirect('/posts')->with('success', 'Пост удален!');
  }
}

resources/views/posts/create.blade.php
@extends('posts.main')

@section('content')
  <div class="mb-5">
    <h3>Напишите свою статью</h3>
  </div>

  <form method="POST" action="{{ route('posts.store') }}">
    @csrf 
    <div class="form-group">
      <label for="exampleFormControlSelect1">Выберите рубрику статьи</label>
      <select class="form-control" name="categories[]" multiple id="exampleFormControlSelect1">
        @forelse($categories as $category)
          <option>{{ $category->name }}</option>
        @empty
          <option>Без категории</option>
        @endforelse
      </select>    
    </div>
    <div class="form-group">
      <label for="exampleInputHeader1">Заголовок статьи</label>
      <input type="name" name="header" class="form-control" value="{{ old('header') }}" id="exampleInputHeader1" aria-describedby="headerHelp">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Текст статьи</label>
      <textarea class="form-control" name="text" id="exampleFormControlTextarea1" rows="5">{{ old('text') }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">Опубликовать</button>
  </form>
@endsection

resources/views/posts/edit.blade.php
@extends('posts.main')

@section('content')
  <div class="mb-3">
    <h3>Отредактируйте вашу статью</h3>
  </div>
  
  <form method="POST" action="{{ route('posts.update', $post) }}">
    @method('PATCH')
    @csrf  
    <div class="form-group">
      <label for="exampleInputEmail1">Текущее имя рубрики</label>
      <input type="name" multiple disabled class="form-control" value="{{ $post->categories()->pluck('name')->implode(', ') }}" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="form-group">
      <label for="exampleFormControlSelect1">Выберите рубрику статьи</label>
      <select class="form-control" name="categories[]" multiple id="exampleFormControlSelect1">
        @forelse($categories as $category)
          <option>{{ $category->name }}</option>
        @empty
          <option>Без категории</option>
        @endforelse
      </select>    
    </div>  
    <div class="form-group">
      <label for="exampleInputEmail1">Заголовок статьи</label>
      <input type="name" name="header" class="form-control" value="{{ $post->header }}" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="form-group">
      <label for="exampleFormControlTextarea1">Текст статьи</label>
      <textarea class="form-control" name="text" id="exampleFormControlTextarea1" rows="5">{{ $post->text }}</textarea>
    </div>  
    <button type="submit" class="btn btn-primary">Опубликовать</button>
  </form>
@endsection

resources/views/posts/index.blade.php
@extends('posts.main')

@section('content')
  <div class="mb-3">
    <h3>Список ваших статей</h3>
  </div>
  <table class="table table-striped table-bordered table-hover mt-3">
    <thead>
      <tr>
        <th scope="col">№</th>
        <th scope="col">Заголовок</th>
        <th scope="col">Рубрика</th>
        <th scope="col">Статья</th>
        <th scope="col" class="th-view">Действия</th>
      </tr>
    </thead>
    <tbody>    
      @foreach($posts as $post)
        <tr>
          <th scope="row">{{ $loop->iteration }}</th>
          <td>{{ $post->header }}</td>
          <td>{{ $post->categories()->pluck('name')->implode(', ') }}</td>
          <td>{{ $post->text }}</td>
          <td class="d-flex justify-content-center">            
            <a href="{{ route('posts.show', $post) }}" class="btn btn-success ml-1">
              <i class="fa fa-eye"> View</i>
            </a>
            <a href="{{ route('posts.edit', $post) }}" class="btn btn-primary ml-1">
              <i class="fa fa-pencil"> Edit</i>
            </a>
            <form class="ml-1" action="{{ route('posts.destroy', $post) }}" method="post">
              @csrf
              @method('DELETE')
              <button type="submit" class="btn btn-danger">
                <i class="fa fa-trash"> Delete</i>
              </button>
            </form>
          </td>
        </tr>
      @endforeach
    </tbody>
  </table>
@endsection

resources/views/posts/main.blade.php
<!doctype html>
<html lang="en">
<head>    
  <title>Заполните форму</title>
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Custom styles for this template -->
  <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
  <!-- BootstrapCDN Font Awesome icons -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <!-- Custom styles for this template -->
  <link href="css/blog.css" rel="stylesheet">
</head>
<body>
  <div class="container">
    <div class="row justify-content-md-center mt-2">
      <div class="col-9">
        
        @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
              @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div><br />
        @endif
        
        @if(session()->get('success'))
          <div class="alert alert-success mt-3">
            {{ session()->get('success') }}
          </div>
        @endif
        
        <div class="mb-2">
          <button class="btn btn-outline-info" type="button" name="button">
            Ваше имя: {{ Auth::user()->name }}
          </button>
          <a class="btn btn-outline-success" href="{{ url('main') }}">Перейти на сайт</a>
          <a class="btn btn-outline-primary" href="{{ route('posts.create') }}">Создать статью</a>
          <a class="btn btn-outline-warning" href="{{ route('posts.index') }}">Перечень ваших статей</a>
        </div>
        
        @yield('content')
        
      </div>
    </div>
  </div>
</body>
</html>

resources/views/posts/show.blade.php
@extends('posts.main')

@section('content')
<a class="btn btn-outline-warning mt-2" href="{{ route('posts.index') }}">Назад к списку статей</a>
<div class="card mt-2">
  <div class="card-body">
    <h3>{{ $post->header }}</h3>
    <p>{{ $post->categories()->pluck('name')->implode(' ') }}</p>
    <p><b>{{ $post->text }}</b></p>
  </div>
</div>
@endsection